export const buttonStyles = {
    bottomButton: {
        position: "fixed",
        padding: 25,
        zIndex: 100,
        transition: "all .8s cubic-bezier(.19,1,.22,1)",
        textDecoration: "none",
        color: "#333333",
        fontWeight: 600,
        border: "none",
        backgroundColor: "transparent",
        cursor: "pointer",
        transform: "translateX(50%) translateY(0)",
    },
    openFooter: {
        transform: "translateX(50%) translateY(-250px) rotate(45deg)",
        position: "fixed",
        padding: 25,
        zIndex: 100,
        transition: "all .8s cubic-bezier(.19,1,.22,1)",
        textDecoration: "none",
        color: "#333333",
        fontWeight: 600,
        border: "none",
        backgroundColor: "transparent",
        cursor: "pointer",
    },
    cartButton: {
        position: 'fixed',
        zIndex: 40,
        transition: 'all .8s cubic-bezier(.19,1,.22,1)',
        textDecoration: 'none',
        color: '#333333',
        fontWeight: 600,
        backgroundColor: 'transparent',
        border: 'none',
        cursor: 'pointer',
        badge: {
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: '0 0 0 2px #f6f6f6',
            bg: 'black',
            color: 'white',
            fontSize: 1,
            fontWeight: 'body',
            borderRadius: '50%',
            position: 'absolute',
            bottom: '1px',
            right: '2px',
            height: '16px',
            minWidth: '16px',
            pt: 0,
            pb: 0,
        }
    }
}